[build]
  publish = "dist"
  command = "npm run build"

[dev]
  command = "npm run dev"
  port = 8888
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "16"
